### ISSUE TITLE
Bash variable expansion doesn't work for me

### ISSUE THREAD

**Issue by d3banjan** [hackerb9/brightness#1]
The tool doesn't work for me.

```bash
$ brightness +10
/usr/local/bin/brightness: line 19: 81
	Brightness: 0.81
	Brightness: 0.81: syntax error in expression (error token is "Brightness: 0.81
	Brightness: 0.81")
/usr/local/bin/brightness: line 21: [[: 81
	Brightness: 0.81
	Brightness: 0.81: syntax error in expression (error token is "Brightness: 0.81
	Brightness: 0.81")
/usr/local/bin/brightness: line 22: [[: 81
	Brightness: 0.81
	Brightness: 0.81: syntax error in expression (error token is "Brightness: 0.81
	Brightness: 0.81")
/usr/local/bin/brightness: line 24: [[: 81
	Brightness: 0.81
	Brightness: 0.81: syntax error in expression (error token is "Brightness: 0.81
	Brightness: 0.81")
xrandr: unrecognized option 'Brightness:'
Try 'xrandr --help' for more information.
xrandr: unrecognized option 'Brightness:'
Try 'xrandr --help' for more information.
xrandr: unrecognized option 'Brightness:'
Try 'xrandr --help' for more information.
```

On closer inspection, this is where the script falls through for me. Why doesn't the transformation not work for multiple lines?

```bash
$ b=$(xrandr --current --verbose | grep Brightness) && echo "$b"
	Brightness: 0.81
	Brightness: 0.81
	Brightness: 0.81

$ echo "${b#*: }"
0.81
	Brightness: 0.81
	Brightness: 0.81
```

**Comment by hackerb9** [comment]
Thanks for the bug report. Changing the # to ## should fix it, I think.

**Comment by hackerb9** [comment]
Okay, I've pushed the patch for it. Let me know if it works. 

Using # only deleted up to the first colon. ## makes it delete in a greedy fashion, deleting as much as possible until the last colon.

**Comment by d3banjan** [comment]
Of course!! You just need the first one!! 

I spent an hour trying to make the shell expansion work for multiple lines without thinking if it is needed.

Just happy that I gave up when I did!

**Comment by hackerb9** [comment]
Yeah, that's a harder problem you worked on. Hopefully you can see it as an hour well spent sharpening your skills. 

Thanks again for the bug report!
